### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by hajaalin** [ome/ome-docker#10]
Hi, 
I loaded the image from Docker Hub and followed the instructions but got an error:

eval $(/opt/multi-config.sh ice35)
OMERO_BRANCH=5.1.1 BUILD_NUMBER=0 sh docs/hudson/OMERO.sh

BUILD FAILED
/build/build.xml:130: The following error occurred while executing this line:
java.io.FileNotFoundException: /build/docs/sphinx/build.xml (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:246)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:177)
	at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:80)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:392)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1360)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1329)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1212)
	at org.apache.tools.ant.Main.runBuild(Main.java:801)
	at org.apache.tools.ant.Main.startAnt(Main.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at omero.startAnt(omero.java:285)
	at omero.main(omero.java:313)

Total time: 15 seconds

It's nice to have this image to get a standard build environment. I now need to rebuild a custom LDAP component that was made for a 4.4.* server.

Best,
Harri

**Comment by manics** [comment]
Which image did you download from Hub? Some of the images are out of date at the moment. We've been doing some clean-up work recently but haven't setup automated builds for everything.

Thanks, Simon

**Comment by joshmoore** [comment]
Is this not more an issue of submodules? What does `git status` show, @hajaalin?

**Comment by hajaalin** [comment]
@manics This is the image as listed by "docker images":
openmicroscopy/omero-build-c6-multienv   latest                                                        1915a80769bd        5 months ago        3.944 GB

**Comment by hajaalin** [comment]
@joshmoore 
```
hajaalin@dx1-biotek973:~/GitHub/openmicroscopy$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.

nothing to commit, working directory clean
```

**Comment by manics** [comment]
What command did you use to checkout the source code?
Could you run `git submodule status`? If the output is prefixed with `-`, e.g.
```
-6e67b78073364f6f259e47f31482ca106713fd2a components/bioformats
-dc0a28f5950d39862b04b7a12a213f2c2b68c208 components/tools/OmeroPy/scripts
-b99ddcfe38500e30eb0d58cc29c02f7ddeddf19b docs/sphinx
```
it means the submodules weren't initialised in which case run
`git submodule init`
`git submodule update`

**Comment by hajaalin** [comment]
I used the command I found in the example on the Docker Hub page. It seems I have the submodules:
```
hajaalin@dx1-biotek973:~/GitHub/openmicroscopy$ git submodule status
 6e67b78073364f6f259e47f31482ca106713fd2a components/bioformats (v5.1.1-60-g6e67b78)
 dc0a28f5950d39862b04b7a12a213f2c2b68c208 components/tools/OmeroPy/scripts (v5.1.1)
 b99ddcfe38500e30eb0d58cc29c02f7ddeddf19b docs/sphinx (v5.1.1-28-gb99ddcf)
```

Ok, now I run the build command again and there is no error. I'm not sure what I did differently. Could be that I didn't restart the build container after I ran git clone --recursive?  If it sounded like submodule error to you, then something like that is probably what happened. 

Thanks for your help, sorry about false alarm!
Harri

**Comment by joshmoore** [comment]
NP, @hajaalin. If you see it again (or if we do), let's try to make it more fail-safe. Cheers.
